### ISSUE TITLE
页面上的"后端地址"能锁死吗？

### ISSUE THREAD

**Issue by zkname** [jwyGithub/subconverter-cloudflare#1]
页面上的"后端地址"能锁死吗？
不要让他选择了，容易错。

**Comment by jwyGithub** [comment]
> 页面上的"后端地址"能锁死吗？ 不要让他选择了，容易错。

已增加环境变量 LOCK_BACKEND ，默认'true'，禁止选择，设置为'false'不禁用

重新部署生效

**Comment by jwyGithub** [comment]
fixed
