### ISSUE TITLE
hy2:// 这种链接不支持，希望优化一下

### ISSUE THREAD

**Issue by qcmoke** [jwyGithub/subconverter-cloudflare#15]
对于 hysteria，目前只支持 hysteria2:// 和 hysteria:// 这两种链接，而 hy2:// 这种链接不支持。
经过测试，肥羊的增强型后端（ https://url.v1.mk ）是支持这三种链接的。
三种测试链接如下：
hysteria2://qwer123@127.0.0.1:31053/?sni=www.bing.com&insecure=1#v2rayN-hy2
hy2://qwer123@127.0.0.1:31053?insecure=1&sni=www.bing.com#nekobox-hy2
hysteria://127.0.0.1:1080?upmbps=100&downmbps=100&peer=www.bing.com#nekobox-hy1

**Comment by jwyGithub** [comment]
已支持
