### ISSUE TITLE
请教大佬，自定义远程配置无效？

### ISSUE THREAD

**Issue by Rangtian** [jwyGithub/subconverter-cloudflare#19]
我设置了[自定义远程配置](https://github.com/liandu2024/clash/blob/main/Clash-LIAN.ini)，可是远程配置列表里没有？

![image](https://github.com/user-attachments/assets/9f1b83dc-8fa2-4c4d-98c0-99d4188647e9)

![image](https://github.com/user-attachments/assets/32ad1b6f-afc4-49aa-b0f1-d801d371e595)

![image](https://github.com/user-attachments/assets/608f3c23-40e8-4ecc-bcd2-70c6cd2a779a)

**Comment by jwyGithub** [comment]
> 我设置了[自定义远程配置](https://github.com/liandu2024/clash/blob/main/Clash-LIAN.ini)，可是远程配置列表里没有？
> 
> ![image](https://private-user-images.githubusercontent.com/22640407/377371703-9f1b83dc-8fa2-4c4d-98c0-99d4188647e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMTM2MjgsIm5iZiI6MTcyOTIxMzMyOCwicGF0aCI6Ii8yMjY0MDQwNy8zNzczNzE3MDMtOWYxYjgzZGMtOGZhMi00YzRkLTk4YzAtOTlkNDE4ODY0N2U5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDAxMDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmOTU0OTE2NTNmNWI2MTM2YzkwNTQzM2Y4MThmMDA1NjNhNmQwM2Y3Mzc1OGFkNGNhMGU0N2IzMjFlZDExYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.w-SKJvIqEOOWGhpeBjmlQuTCE-xbbErzeSzJw4Zi3W4)
> 
> ![image](https://private-user-images.githubusercontent.com/22640407/377372071-32ad1b6f-afc4-49aa-b0f1-d801d371e595.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMTM2MjgsIm5iZiI6MTcyOTIxMzMyOCwicGF0aCI6Ii8yMjY0MDQwNy8zNzczNzIwNzEtMzJhZDFiNmYtYWZjNC00OWFhLWIwZjEtZDgwMWQzNzFlNTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDAxMDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyMWNmMDdjYzAyZWQ2NTI0NDI5ZmEyNjM1N2QxZTAxNGU2MmZkODAwZjkxYTQ0OWIyN2U0M2UzY2JhZTUwZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GKQ3VbaV12Zaka0EBu4BZFHzOxQ663jsaP5SKqPYsoE)
> 
> ![image](https://private-user-images.githubusercontent.com/22640407/377373926-608f3c23-40e8-4ecc-bcd2-70c6cd2a779a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMTM2MjgsIm5iZiI6MTcyOTIxMzMyOCwicGF0aCI6Ii8yMjY0MDQwNy8zNzczNzM5MjYtNjA4ZjNjMjMtNDBlOC00ZWNjLWJjZDItNzBjNmNkMmE3NzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDAxMDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MGQ5MTkzYzBjMDAyNzk2NjYyZGNiZWI0NDAyNTdmMTE4ZjQyYTAyNWQwNzM4YWVlZmE3MzA0OWY2MzRhM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hrYLu3VdUoWz10AbRLJUzR7YAQRTjFmGmp9xrhjhOls)

可以发下你的部署url吗？我测试了是可以添加的
<img width="1446" alt="image" src="https://github.com/user-attachments/assets/bc61924b-5895-4d26-8e9a-2c1eb3c2e365">

**Comment by Rangtian** [comment]
> > 我设置了[自定义远程配置](https://github.com/liandu2024/clash/blob/main/Clash-LIAN.ini)，可是远程配置列表里没有？
> > ![image](https://private-user-images.githubusercontent.com/22640407/377371703-9f1b83dc-8fa2-4c4d-98c0-99d4188647e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMTM2MjgsIm5iZiI6MTcyOTIxMzMyOCwicGF0aCI6Ii8yMjY0MDQwNy8zNzczNzE3MDMtOWYxYjgzZGMtOGZhMi00YzRkLTk4YzAtOTlkNDE4ODY0N2U5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDAxMDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmOTU0OTE2NTNmNWI2MTM2YzkwNTQzM2Y4MThmMDA1NjNhNmQwM2Y3Mzc1OGFkNGNhMGU0N2IzMjFlZDExYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.w-SKJvIqEOOWGhpeBjmlQuTCE-xbbErzeSzJw4Zi3W4)
> > ![image](https://private-user-images.githubusercontent.com/22640407/377372071-32ad1b6f-afc4-49aa-b0f1-d801d371e595.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMTM2MjgsIm5iZiI6MTcyOTIxMzMyOCwicGF0aCI6Ii8yMjY0MDQwNy8zNzczNzIwNzEtMzJhZDFiNmYtYWZjNC00OWFhLWIwZjEtZDgwMWQzNzFlNTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDAxMDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyMWNmMDdjYzAyZWQ2NTI0NDI5ZmEyNjM1N2QxZTAxNGU2MmZkODAwZjkxYTQ0OWIyN2U0M2UzY2JhZTUwZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GKQ3VbaV12Zaka0EBu4BZFHzOxQ663jsaP5SKqPYsoE)
> > ![image](https://private-user-images.githubusercontent.com/22640407/377373926-608f3c23-40e8-4ecc-bcd2-70c6cd2a779a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMTM2MjgsIm5iZiI6MTcyOTIxMzMyOCwicGF0aCI6Ii8yMjY0MDQwNy8zNzczNzM5MjYtNjA4ZjNjMjMtNDBlOC00ZWNjLWJjZDItNzBjNmNkMmE3NzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDAxMDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MGQ5MTkzYzBjMDAyNzk2NjYyZGNiZWI0NDAyNTdmMTE4ZjQyYTAyNWQwNzM4YWVlZmE3MzA0OWY2MzRhM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hrYLu3VdUoWz10AbRLJUzR7YAQRTjFmGmp9xrhjhOls)
> 
> 可以发下你的部署url吗？我测试了是可以添加的 <img alt="image" width="1446" src="https://private-user-images.githubusercontent.com/58636312/377678444-bc61924b-5895-4d26-8e9a-2c1eb3c2e365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNTI1ODgsIm5iZiI6MTcyOTI1MjI4OCwicGF0aCI6Ii81ODYzNjMxMi8zNzc2Nzg0NDQtYmM2MTkyNGItNTg5NS00ZDI2LThlOWEtMmMxZWIzYzJlMzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDExNTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmZDRmN2U1NTg5MjNkYzExNGUzOGI3MGM3YzY2NTYyZjYwYzlmNDIxZjdlZTUxZDNhZjk3YTEyNDI5YzE4MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fEoc6KP9zVFdeHyyhm0xjjjjkdnWyq9-ke_CoqzCEOU">

大佬您好，链接：https://sub.myladder.eu.org/

我是按照不良林的视频操作的。这 html 的格式也是乱的，请问是我哪里搞错了么？

![image](https://github.com/user-attachments/assets/8c0b2120-6c4b-46f8-aa92-66a73118cea7)

**Comment by jwyGithub** [comment]
> https://sub.myladder.eu.org/

因为你的页面资源没加载出来，所以样式没生效，导致页面错乱，键盘按F12，看下控制台的报错

你看下你本地的网络环境是否能加载这几个资源
https://cdn.bootcdn.net/ajax/libs/element-ui/2.15.14/theme-chalk/index.min.css
https://cdn.bootcdn.net/ajax/libs/element-ui/2.15.14/theme-chalk/fonts/element-icons.woff

我这里打开你的url是正常的


<img width="1412" alt="image" src="https://github.com/user-attachments/assets/654db7ce-a293-4b90-98e6-3945263569fa">

**Comment by Rangtian** [comment]
> > https://sub.myladder.eu.org/
> 
> 因为你的页面资源没加载出来，所以样式没生效，导致页面错乱，键盘按F12，看下控制台的报错
> 
> 你看下你本地的网络环境是否能加载这几个资源 https://cdn.bootcdn.net/ajax/libs/element-ui/2.15.14/theme-chalk/index.min.css https://cdn.bootcdn.net/ajax/libs/element-ui/2.15.14/theme-chalk/fonts/element-icons.woff
> 
> 我这里打开你的url是正常的
> <img alt="image" width="1412" src="https://private-user-images.githubusercontent.com/58636312/378037150-654db7ce-a293-4b90-98e6-3945263569fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMTY3NjEsIm5iZiI6MTcyOTMxNjQ2MSwicGF0aCI6Ii81ODYzNjMxMi8zNzgwMzcxNTAtNjU0ZGI3Y2UtYTI5My00YjkwLTk4ZTYtMzk0NTI2MzU2OWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDA1NDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZDZiYTQyYTQ0OThiOTJhMjcwYjFkNGI4ZjU2YmVlMTVlNjMwMDQ0MGQ3MGFmN2I1ZDMwNDU0ZThmNjhmY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UuNOvftX_pKTwX9th0aL_OfEZ3rLDgJXhCYBWYO81Qk">

确实是因为资源没加载出来，相关链接没有走代理。感谢大佬！
