### ISSUE TITLE
REMOTE_CONFIG 自定义配置 http: 被截断了。 和内容:冲突了。

### ISSUE THREAD

**Issue by zkname** [jwyGithub/subconverter-cloudflare#2]
REMOTE_CONFIG 自定义配置 http: 被截断了。 和内容:冲突了。

**Comment by zkname** [comment]
配置:https://github.com/jwyGithub/subconverter-cloudflare/issues/2
URL 变成 https了 &config=https&

**Comment by jwyGithub** [comment]
> 配置:#2 URL 变成 https了 &config=https&

已修复
