### ISSUE TITLE
Invalid request!

### ISSUE THREAD

**Issue by Rangtian** [jwyGithub/subconverter-cloudflare#21]
[https://sub.id9.cc](https://sub.id9.cc) 用了不到1小时就崩了，Cloudflare显示 id9.cc 宕机了。
[https://sub.xeton.dev](https://sub.xeton.dev) 目前可用。

-----------------------------------------------------------------------------

大佬你好！使用默认的BACKEND [https://url.v1.mk](https://url.v1.mk/) CF生成的订阅转换链接，在浏览器中打开，刚开始可以获取分组与规则，但节点为空。

多订阅几次后，什么都无法获取了，显示 **Invalid request!**

直接使用 [https://sub.v1.mk/](https://sub.v1.mk/) 可以正常转换订阅。

![图片](https://github.com/user-attachments/assets/43a8402d-fdbe-44e2-adbc-c4dfb8afd126)

![图片](https://github.com/user-attachments/assets/2908644a-cda8-4832-8565-7fac9ee8c819)

**Comment by jwyGithub** [comment]
目前这个版本的转换规则存在问题，经测试会存在偶尔丢失节点的情况，项目已经在重构阶段，新项目目前只支持混淆ss,vmess,vless,trojan,订阅链接混淆正在开发中，可以暂时使用就项目的版本

**Comment by Rangtian** [comment]
> 目前这个版本的转换规则存在问题，经测试会存在偶尔丢失节点的情况，项目已经在重构阶段，新项目目前只支持混淆ss,vmess,vless,trojan,订阅链接混淆正在开发中，可以暂时使用就项目的版本

大佬牛哔，给您打Call
