### ISSUE TITLE
部署时报错

### ISSUE THREAD

**Issue by lxt20180608** [jwyGithub/subconverter-cloudflare#4]
API Request Failed: PUT /api/v4/accounts/........./environments/production?include_subdomain_availability=true (403)

请问这是账号问题还是代码问题？

**Comment by jwyGithub** [comment]
> API Request Failed: PUT /api/v4/accounts/........./environments/production?include_subdomain_availability=true (403)
> 
> 请问这是账号问题还是代码问题？

你部署的时候是不是开了vps？  这个错误一般是使用cf的vps，然后反向代理配置错误引起的

**Comment by lxt20180608** [comment]
> > API Request Failed: PUT /api/v4/accounts/........./environments/production?include_subdomain_availability=true (403)
> 
> > 
> 
> > 请问这是账号问题还是代码问题？
> 
> 
> 
> 你部署的时候是不是开了vps？  这个错误一般是使用cf的vps，然后反向代理配置错误引起的

您说的是vpn吗？我关了vpn也不行，没有用反向代理

**Comment by jwyGithub** [comment]
> > > API Request Failed: PUT /api/v4/accounts/........./environments/production?include_subdomain_availability=true (403)
> > 
> > 
> > > 
> > 
> > 
> > > 请问这是账号问题还是代码问题？
> > 
> > 
> > 你部署的时候是不是开了vps？  这个错误一般是使用cf的vps，然后反向代理配置错误引起的
> 
> 您说的是vpn吗？我关了vpn也不行，没有用反向代理

目前排查出来是由于代码问题，可以暂时使用fork的方式进行部署

**Comment by lxt20180608** [comment]
> > > > API Request Failed: PUT /api/v4/accounts/........./environments/production?include_subdomain_availability=true (403)
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 请问这是账号问题还是代码问题？
> > > 
> > > 
> > > 你部署的时候是不是开了vps？  这个错误一般是使用cf的vps，然后反向代理配置错误引起的
> > 
> > 
> > 您说的是vpn吗？我关了vpn也不行，没有用反向代理
> 
> 目前排查出来是由于代码问题，可以暂时使用fork的方式进行部署

好的，感谢
