### ISSUE TITLE
Fork部署之后后端地址不正确

### ISSUE THREAD

**Issue by lxt20180608** [jwyGithub/subconverter-cloudflare#5]
如图所示，订阅页面后端显示不正确，变量名均已配置，且加了自定义域名

![image](https://github.com/user-attachments/assets/8d80f1db-2cac-497b-9af6-19dd81588afb)

![image](https://github.com/user-attachments/assets/27d57e6c-f77a-4870-be8f-1e6e258dc775)

![image](https://github.com/user-attachments/assets/2e773fbf-9aa0-4f0d-8894-b3dccd635eea)

**Comment by jwyGithub** [comment]
正在排查问题

**Comment by jwyGithub** [comment]
> 如图所示，订阅页面后端显示不正确，变量名均已配置，且加了自定义域名
> 
> ![image](https://private-user-images.githubusercontent.com/61131978/352421108-8d80f1db-2cac-497b-9af6-19dd81588afb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMTU1NDEsIm5iZiI6MTcyMjIxNTI0MSwicGF0aCI6Ii82MTEzMTk3OC8zNTI0MjExMDgtOGQ4MGYxZGItMmNhYy00OTdiLTlhZjYtMTlkZDgxNTg4YWZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDAxMDcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4OTY4ZjUyOWQ4ZGIyY2YxODI5OGJmN2U2NmE5YjAwZWY1OWJjOTFmZjM4ODZjNWNkOTA4ZjRmZmJkZWNmZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zDQgZwhNMrepVPnEYSZfcvL6AfLLgS0Hdu237o-rvls)
> 
> ![image](https://private-user-images.githubusercontent.com/61131978/352421882-27d57e6c-f77a-4870-be8f-1e6e258dc775.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMTU1NDEsIm5iZiI6MTcyMjIxNTI0MSwicGF0aCI6Ii82MTEzMTk3OC8zNTI0MjE4ODItMjdkNTdlNmMtZjc3YS00ODcwLWJlOGYtMWU2ZTI1OGRjNzc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDAxMDcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyOTMxMTFlYmM2MjExYzAwZWJmYTI3YWI5MGFhM2JkNDI4MDIxMTcyYmYyMDc3NjcxYTRkZTA1N2I0MDJjZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jrPJAd934IhEAfm1xIb97Zj2nCE5vzSs5tcKKRuK3uI)
> 
> ![image](https://private-user-images.githubusercontent.com/61131978/352422084-2e773fbf-9aa0-4f0d-8894-b3dccd635eea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMTU1NDEsIm5iZiI6MTcyMjIxNTI0MSwicGF0aCI6Ii82MTEzMTk3OC8zNTI0MjIwODQtMmU3NzNmYmYtOWFhMC00ZjBkLTg4OTQtYjNkY2NkNjM1ZWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDAxMDcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMGI2Yzk1ZjBhNThiMWRhYTMwNTI5Y2E1Y2YxMDEyNzJjZmQ4N2ZkM2ZkMTE4YzU3YzhhYTJiYTM4NzMwMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GjQYRF2ET8-ySaokl42E1rr2fum6076EcT7-zmUeTj8)

已解决，通过worker重新部署即可

**Comment by zxlhhyccc** [comment]
订阅页面后端仍然显示不正确，变量名均已配置，且加了自定义域名。
![image](https://github.com/user-attachments/assets/6030d0ca-5e87-4009-b951-34efd86a48cc)
![image](https://github.com/user-attachments/assets/5d9b220c-e410-455a-94c6-c14f0d05e4bd)
![image](https://github.com/user-attachments/assets/96d39263-2b19-4ff8-ad83-823cbd5eb44b)

**Comment by lxt20180608** [comment]
> > 如图所示，订阅页面后端显示不正确，变量名均已配置，且加了自定义域名
> > ![image](https://private-user-images.githubusercontent.com/61131978/352421108-8d80f1db-2cac-497b-9af6-19dd81588afb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMTU1NDEsIm5iZiI6MTcyMjIxNTI0MSwicGF0aCI6Ii82MTEzMTk3OC8zNTI0MjExMDgtOGQ4MGYxZGItMmNhYy00OTdiLTlhZjYtMTlkZDgxNTg4YWZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDAxMDcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4OTY4ZjUyOWQ4ZGIyY2YxODI5OGJmN2U2NmE5YjAwZWY1OWJjOTFmZjM4ODZjNWNkOTA4ZjRmZmJkZWNmZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zDQgZwhNMrepVPnEYSZfcvL6AfLLgS0Hdu237o-rvls)
> > ![image](https://private-user-images.githubusercontent.com/61131978/352421882-27d57e6c-f77a-4870-be8f-1e6e258dc775.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMTU1NDEsIm5iZiI6MTcyMjIxNTI0MSwicGF0aCI6Ii82MTEzMTk3OC8zNTI0MjE4ODItMjdkNTdlNmMtZjc3YS00ODcwLWJlOGYtMWU2ZTI1OGRjNzc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDAxMDcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyOTMxMTFlYmM2MjExYzAwZWJmYTI3YWI5MGFhM2JkNDI4MDIxMTcyYmYyMDc3NjcxYTRkZTA1N2I0MDJjZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jrPJAd934IhEAfm1xIb97Zj2nCE5vzSs5tcKKRuK3uI)
> > ![image](https://private-user-images.githubusercontent.com/61131978/352422084-2e773fbf-9aa0-4f0d-8894-b3dccd635eea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMTU1NDEsIm5iZiI6MTcyMjIxNTI0MSwicGF0aCI6Ii82MTEzMTk3OC8zNTI0MjIwODQtMmU3NzNmYmYtOWFhMC00ZjBkLTg4OTQtYjNkY2NkNjM1ZWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDAxMDcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMGI2Yzk1ZjBhNThiMWRhYTMwNTI5Y2E1Y2YxMDEyNzJjZmQ4N2ZkM2ZkMTE4YzU3YzhhYTJiYTM4NzMwMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GjQYRF2ET8-ySaokl42E1rr2fum6076EcT7-zmUeTj8)
> 
> 已解决，通过worker重新部署即可

图挂了,使用新版的worker解决了问题，感谢大佬分享

**Comment by zxlhhyccc** [comment]
> 图挂了,使用新版的worker解决了问题，感谢大佬分享

请问你是怎么解决的？

**Comment by lxt20180608** [comment]
> > 图挂了,使用新版的worker解决了问题，感谢大佬分享
> 
> 请问你是怎么解决的？

不要fork部署，直接按照不良林原来的教程，代码用这个大佬的

**Comment by zxlhhyccc** [comment]
你的意思是用worker部署对吗？
后端地址已设置但未起作用：
![image](https://github.com/user-attachments/assets/4644c936-4d7c-4ac1-9fc2-050498cb1202)
已设置的后端地址：
![image](https://github.com/user-attachments/assets/e63e1cce-2216-4af0-8b22-6a34bf4f13cb)

![image](https://github.com/user-attachments/assets/e1ef1e2f-50c4-4a3d-8b4c-c3bddcb46478)

**Comment by zxlhhyccc** [comment]
新代码现在无法获取短链接。。。仓库里的演示连接也是一样。。。
![image](https://github.com/user-attachments/assets/745100f1-7549-44b3-b75e-d31d0dd57beb)

**Comment by lxt20180608** [comment]
> 你的意思是用worker部署对吗？ 后端地址已设置但未起作用： ![image](https://private-user-images.githubusercontent.com/45259624/352933003-4644c936-4d7c-4ac1-9fc2-050498cb1202.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMDgyMjQsIm5iZiI6MTcyMjMwNzkyNCwicGF0aCI6Ii80NTI1OTYyNC8zNTI5MzMwMDMtNDY0NGM5MzYtNGQ3Yy00YWMxLTlmYzItMDUwNDk4Y2IxMjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDAyNTIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZWRhZDRjMTMwNzA3ZDNlNjliYWY1MzE2ZDAwNzBjNDRhOWYwZDEyYmY4NTBhZDljMmIyZDcxODFiOWQwY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uujihPRAqSPfqr96NhlLxg9qOkogK54rH3VyxsdPvNY) 已设置的后端地址： ![image](https://private-user-images.githubusercontent.com/45259624/352933084-e63e1cce-2216-4af0-8b22-6a34bf4f13cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMDgyMjQsIm5iZiI6MTcyMjMwNzkyNCwicGF0aCI6Ii80NTI1OTYyNC8zNTI5MzMwODQtZTYzZTFjY2UtMjIxNi00YWYwLThiMjItNmEzNGJmNGYxM2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDAyNTIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzODlkZTgxMmZiNzAwYTQ4YWNkZjhhYzAzMWZjZjhlNDAzZjAzMjYyZWUyZTU3YjkzMTNmYjcwZDIyM2QxZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e76xKPbzZCoZq6Agd96n3gjSvdxYh0LHAUFURQB-RCk)
> 
> ![image](https://private-user-images.githubusercontent.com/45259624/353075194-e1ef1e2f-50c4-4a3d-8b4c-c3bddcb46478.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMDgyMjQsIm5iZiI6MTcyMjMwNzkyNCwicGF0aCI6Ii80NTI1OTYyNC8zNTMwNzUxOTQtZTFlZjFlMmYtNTBjNC00YTNkLThiNGMtYzNiZGRjYjQ2NDc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDAyNTIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3NTM2ODRhYTViMzU4ZGQyMmRhMWUyYzg4NjVjYmNlMWM0ZmVkMDJiMDQ0MzI2YjA0M2NhMWU1N2M2M2YwMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uAH_x8ocgv2K0km12U7Fq6XpWHweRzGQ6KdBIB55jRA)

你这个后端地址是正确的，变量里的后端是真实后端地址，演示图里面的是一个寄生的，但你这个为什么打不开我也不清楚

**Comment by zxlhhyccc** [comment]
@lxt20180608 大佬，我部署了不良林的那个pusb，是不是有冲突？另外，可以通过page部署这个订阅转换，需要将worker改为_worker即可。。。

**Comment by zxlhhyccc** [comment]
@jwyGithub 大佬，能否比照这个仓库修改一下代码，我用你的仓库无法转换。。。
https://github.com/Andy-github999/psub/tree/main

**Comment by lxt20180608** [comment]
> @lxt20180608 大佬，我部署了不良林的那个pusb，是不是有冲突？另外，可以通过page部署这个订阅转换，需要将worker改为_worker即可。。。

不良林和[jwyGithub](https://github.com/jwyGithub)的只能部署一个，是会冲突

**Comment by zxlhhyccc** [comment]
@lxt20180608 你的能转换订阅吗？大佬代码中的KV空间绑定应该是有问题，搞不明白你的怎么可以转换了。现在我修改了KV空间补丁的对应代码，目前一切一切正常，我已经提了pr，看大佬合并不合并了，我也贴出了日志，提示就是KV空间绑定问题导致无法订阅转换。。

**Comment by lxt20180608** [comment]
可以转换，没有问题

@zxlhhyccc
